<?php

namespace Domain\Auth\Providers;


use Illuminate\Support\ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{

    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->register(
            ActionServiceProvider::class,
        );
    }
}
